# Generated by Django 3.1.5 on 2021-09-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=50)),
                ('problem_desc', models.TextField(max_length=1000)),
                ('date_and_time', models.DateTimeField(blank=True)),
            ],
        ),
    ]
